### ISSUE TITLE
Replace `lazy_static` with `once_cell::Lazy`

### ISSUE THREAD

**Issue by cloudhead** [cloudhead/nakamoto#104]
The latter is becoming standardized.

**Comment by vincenzopalazzo** [comment]
Maybe we could also move the implementation to the experimental one without importing new dependencies?

I used the rustc version and it works pretty well and looks stable enough, but the API looks like different from the `once_clell` I need to make double-check with the rust lib team on the stabilization road map of this feature

https://github.com/vincenzopalazzo/rio/blob/main/rt/src/runitime.rs#L79

**Comment by cloudhead** [comment]
How would that work? Doesn't it require nightly?

**Comment by vincenzopalazzo** [comment]
Yes for now yes https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021
