### ISSUE TITLE
Slow block cache loading and filter header verification

### ISSUE THREAD

**Issue by ghost** [cloudhead/nakamoto#119]
The following two calls:

https://github.com/cloudhead/nakamoto/blob/456cc8f45a6e8425c4ab074e175e5120097d0d26/client/src/client.rs#L301

https://github.com/cloudhead/nakamoto/blob/456cc8f45a6e8425c4ab074e175e5120097d0d26/client/src/client.rs#L333

Are painfully slow in debug mode with the situation somewhat improving in release mode (thought not great). Both take upward of tens of seconds to complete for the current testnet blockchain. Are these potentially doing lots of real time disk IO instead of loading in chunks? That might not be it but both seem to call `iter().enumerate()` on a store, which seems to be backed by a `File`.

**Comment by cloudhead** [comment]
Is this a regression introduced by the loading event channel? Or does the issue predate that change?

The block header loading does sequential disk access on a file. I could see if we can get a speed-up by loading in chunks.

**Comment by cloudhead** [comment]
Ok, yes there's various things we can do, I'm going to look into it.

**Comment by cloudhead** [comment]
Batching the reads gives me a speed up from 3.5s to 2.5s in release mode.. I don't think it's worthwhile, so will look into maybe just skipping parts of header verification.

**Comment by cloudhead** [comment]
Yup, after profiling, it looks like 90% of the time is spent in the `BlockHeader::block_hash` function, which is called once per header. This hash is computed to build a `Hash -> Header` index for fast retrieval.

If I remove the hashing, loading time goes from 2.5s to 200ms, so a more than 10x speedup!

We may be able to use the parent hashes to avoid hashing everything.

**Comment by cloudhead** [comment]
Ok, see here: https://github.com/cloudhead/nakamoto/pull/120

This doesn't touch filter verification, so that's still something that I could look at.

**Comment by cloudhead** [comment]
Awesome. Yes, filter header verification could be skipped or made optional even as a first step, and we could use a checksum as an improvement on that.

**Comment by cloudhead** [comment]
Ok, made some changes and opened https://github.com/cloudhead/nakamoto/pull/122

I've opted for making it `false` by default, since in most cases it isn't needed. I've also changed it to `verify`, as I will bundle other verifications under it, ie. not just filter verification.
