### ISSUE TITLE
How do I know if the node is synced?

### ISSUE THREAD

**Issue by danielabrozzoni** [cloudhead/nakamoto#134]
Hi,
I'm building a wallet-like application using nakamoto. The structure is a bit weird, but basically, I need to sync with the blockchain only when the user triggers the `sync` command. Every time the user calls sync, I block everything I'm doing, I start nakamoto, and I shut it down when I'm "synced", i.e., I received all the last block mined by the Bitcoin network.
As far as I can understand, I have no way of knowing when I'm synced from the `Events`, is that correct? At the moment I'm thinking of shutting down the node when I haven't received a `BlockConnected` event in a while (~30 seconds?), is there a better way of accomplishing the same result?

**Comment by vincenzopalazzo** [comment]
You could store the max `PeerHeightUpdated` received so only in this way do you know a possible height.

I have the same use case to implement in core lightning backend, with @cloudhead we discuss a similar approach, so I guess we need just to implement it and see how it goes

**Comment by danielabrozzoni** [comment]
Awesome, thanks!

**Comment by cloudhead** [comment]
If you're doing a rescan, you can use the `Event::Synced` event, but if you are simply waiting for all headers to be downloaded, then yeah I'd suggest what @vincenzopalazzo suggested. I think I will eventually have a dedicated event for this though.
