### ISSUE TITLE
nakamoto failing to broadcast transaction on Signet

### ISSUE THREAD

**Issue by cygnet3** [cloudhead/nakamoto#154]
I've constructed a simple transaction using Sparrow:
```
02000000000101ea71aa519688d485f3f95df6a435fb941a51c04f0c9e9418fbf4c334529152440000000000fdffffff01b608000000000000160014790a03bd375664b1773589672ab71d713ac025a402473044022056b6c29ad3d306170e26fa9d57de62e2113d7458a8bd1fda66f9f727cd16e7dd022026f495ebae9728c76daa8b62ed5dedc1fb17b0127b851891324e2bcd41c736be012103333e1cb8acdeb54a1390b9c9fda6b4e3dcb019304119a4eb97aab4bb480c2827e5d20200
```

When I try to broadcast this transaction with nakamoto:

```rust
     let tx = Transaction::deserialize(hex::decode(tx_byte_str).unwrap().as_slice()).unwrap();
     let res = handle.submit_transaction(tx).unwrap();
```

It successfully returns, showing 3 different peers to which it broadcasted the transaction. However, it doesn't look like the transaction gets propagated over the network.

Some things I've tried:
- checking if there's something wrong with the transaction using `testmempoolaccept` (looks all right)
- Importing the transaction in Sparrow and broadcasting it, this works
- Broadcasting the transaction to an electrum server using [electrum client broadcast](https://docs.rs/electrum-client/latest/src/electrum_client/client.rs.html#322-324), this works
- adding my own signet node to nakamoto as a peer and broadcasting the transaction to it, then calling `getrawtransaction` to see if it's in my node's mempool, no luck
- Using testnet instead of signet

I suspect either something goes wrong while deserializing the transaction (though this doesn't give any errors either), or nakamoto doesn't broadcast the transaction for some reason.

**Comment by Sosthene00** [comment]
This was fundamentally a misconception of how nakamoto is working, I was assuming that we were broadcasting the transaction to the peers and that as soon as we got the `Ok()` return from the function this was done, but according to the bitcoin p2p protocol we actually first send an `inv` message with the txid, the peers (normally) don't know about it and ask us the whole transaction with a `getdata` message. By returning and shutting down nakamoto immediately we weren't leaving them the time to do the whole process.
