### ISSUE TITLE
Compiling error

### ISSUE THREAD

**Issue by fmarcosh** [cloudhead/nakamoto#16]
In a Ubuntu 20.04 LTS on Windows Subsystem Linux v2 I got the following error with cargo build:
   Compiling nakamoto-p2p v0.2.0 (/home/paco/nakamoto/p2p)
error[E0658]: use of unstable library feature 'range_is_empty': recently added
   --> p2p/src/protocol/spvmgr.rs:541:30
    |
541 |         debug_assert!(!range.is_empty());
    |                              ^^^^^^^^
    |
    = note: see issue #48111 <https://github.com/rust-lang/rust/issues/48111> for more information

error[E0658]: use of unstable library feature 'range_is_empty': recently added
   --> p2p/src/protocol/spvmgr.rs:543:18
    |
543 |         if range.is_empty() {
    |                  ^^^^^^^^
    |
    = note: see issue #48111 <https://github.com/rust-lang/rust/issues/48111> for more information

error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0658`.
error: could not compile `nakamoto-p2p`.

To learn more, run the command again with --verbose.

**Comment by cloudhead** [comment]
I'm guessing you're using an older version of `rustc`. `Range::is_empty` was added in 1.47

**Comment by fmarcosh** [comment]
You're right rustc versión is 1.43. thank you.

Obtener Outlook para Android<https://aka.ms/ghei36>

________________________________

**Comment by fmarcosh** [comment]
Sorry. I was using a rustc version 1.43.
