### ISSUE TITLE
Update protocol version & improve handling

### ISSUE THREAD

**Issue by cloudhead** [cloudhead/nakamoto#44]
Since rust-bitcoin cannot serialize txs without witness data, we should be requiring at least 70013, and sending the highest possible version that we support.

This wasn't done previously due to missing `sendcmpct` support, though that is probably fixed.

We should also split the protocol version into what we offer, vs. what we require from peers.

**Comment by cloudhead** [comment]
@vincenzopalazzo this could be a good issue for you to take on. I can add a little more context if you're interested.

**Comment by vincenzopalazzo** [comment]
I was thinking the same things before. Let start from here 😬.

concept ack.

Thanks

**Comment by cloudhead** [comment]
Maybe some inspiration here: https://github.com/stevenroose/rust-bitcoin-p2p/blob/master/src/logic/handshake.rs#L88

**Comment by cloudhead** [comment]
This was fixed in #51
