### ISSUE TITLE
Publish latest release in crates.io

### ISSUE THREAD

**Issue by rajarshimaitra** [cloudhead/nakamoto#90]
Currently the version available for crates.io is `v0.2.0`. https://crates.io/crates/nakamoto

Which is a old revision and doesn't fit with the latest examples usage API in the `wallet` crate.. I am currently working with a local snapshot at commit `b17f93cdb3fa824cd1601809ab5ddefa32f2757b`. 

It would be really helpful if we can get the `v0.3.0` in crates.io..

**Comment by cloudhead** [comment]
Yup, good idea.

**Comment by cloudhead** [comment]
Latest (0.3.0) has now been published to crates.io.
